chore(deps): update to yauzl: '^3.3.1' for electron install (#17623)
### What does this PR do?

There are issues when installing electron / using `pnpm watch`.

```
pnpm watch

> podman-desktop@1.28.0-next watch /Users/vladimirlazar/repos/podman-desktop
> node scripts/watch.mjs

Downloading Electron binary...
node:fs:441
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/vladimirlazar/repos/podman-desktop/node_modules/electron/path.txt'
    at Object.readFileSync (node:fs:441:20)
    at getElectronPath (/Users/vladimirlazar/repos/podman-desktop/node_modules/electron/index.js:47:25)
    at Object.<anonymous> (/Users/vladimirlazar/repos/podman-desktop/node_modules/electron/index.js:52:18)
    at Module._compile (node:internal/modules/cjs/loader:1854:14)
    at Object..js (node:internal/modules/cjs/loader:1985:10)
    at Module.load (node:internal/modules/cjs/loader:1577:32)
    at Module._load (node:internal/modules/cjs/loader:1379:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at loadCJSModuleWithModuleLoad (node:internal/modules/esm/translators:326:3)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:231:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/vladimirlazar/repos/podman-desktop/node_modules/electron/path.txt'
}

Node.js v24.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

There is an upstream issue here: where this is failing on the newer
electron verisons and node: https://github.com/electron/electron/issues/51619

### Screenshot / video of UI

<!-- If this PR is changing UI, please include
screenshots or screencasts showing the difference -->

N/;A

### What issues does this PR fix or reference?

<!-- Include any related issues from Podman Desktop
repository (or from another issue tracker). -->

https://github.com/electron/electron/issues/51619

### How to test this PR?

<!-- Please explain steps to verify the functionality,
do not forget to provide unit/component tests -->

`rm -rf node_modules && rm -rf pnpm-lock.yaml && pnpm install`

and then

`pnpm watch`

and you should be able to use it now.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>